# Generated by Django 2.1.4 on 2018-12-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='classroom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='lesson',
            unique_together={('day', 'number', 'teacher', 'subject', 'week', 'group', 'classroom')},
        ),
    ]
