# Generated by Django 2.1.4 on 2018-12-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulerapp', '0004_auto_20181225_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='week',
            field=models.IntegerField(choices=[(0, 'Всі'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, 'Непарні'), (6, 'Парні')], default=0),
        ),
    ]
