# Generated by Django 2.2.6 on 2020-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='term start date')),
                ('end', models.DateField(verbose_name='term end date')),
            ],
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='group',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='second_teacher',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='lessoninfo',
            name='teacher',
        ),
    ]
