# Generated by Django 2.2.6 on 2020-01-27 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200116_1426'),
        ('info', '0002_auto_20200127_1336'),
        ('scheduler', '0002_auto_20200127_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonInfo',
        ),
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='users.Group'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='second_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_lessons', to='info.Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='info.Subject'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_lessons', to='info.Teacher'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='info.Term'),
        ),
    ]
