# Generated by Django 2.2.6 on 2019-12-18 10:39

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'MONDAY'), (2, 'TUESDAY'), (3, 'WEDNESDAY'), (4, 'THURSDAY'), (5, 'FRIDAY')], default=1, verbose_name='weekday')),
                ('weeks', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]), default=list, size=4, verbose_name='weeks')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(7)], verbose_name='number')),
                ('type', models.CharField(choices=[('lecture', 'LECTURE'), ('lab', 'LAB')], default='lecture', max_length=10, verbose_name='lesson type')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='info.Classroom')),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='info.LessonInfo')),
            ],
            options={
                'ordering': ('day', 'number'),
                'unique_together': {('day', 'number', 'weeks', 'classroom')},
            },
        ),
    ]
